version: "3.2"

services:

  attendence:
    image: zohoattendence:latest
    build:
      context: .
    restart: always
    entrypoint: python3
    command: app.py
    volumes:
      - $FIREFOX_PROFILE:/app/profile
      - ./config.ini:/app/config.ini
      - ./mydata:/app/mydata